---
title: "Reunindo cientistas brasileiros para compartilhar dados do solo"
date: "2018-01-30"
categories: ["publicação"]
banner: "img/banners/banner-02.png"
author: "Alessandro Samuel-Rosa"
---

O Repositório Brasileiro Livre para Dados Abertos do Solo é fruto do trabalho de dezenas de pessoas das diversas instituições de ensino superior e pesquisa. Para contar ao mundo sobre nossa experiência, submetemos um resumo ao 21° Congresso Mundial de Ciência do Solo ([21WCSS][wcss]), que será realizado na cidade do Rio de Janeiro entre os dias 17 e 21 de agosto de 2018. Como o sistema de submissão de resumos do 21WCSS limita o número de autores a um máximo de 15, nós publicando aqui, além do resumo, a lista completa de autores e suas respectivas instituições. Os nomes e insituições em destaque são aqueles incluídos no resumo submetibo. Uma versão expandida desse resumo está sendo preparada para a XII Reunião Sul Brasileira de Ciência do Solo ([XIIRSBCS][rsbcs]), que ocorre nos dias 15, 16 e 17 de abril de 2018 na cidade de Xanxerê, SC.

[wcss]: https://www.21wcss.org/
[rsbcs]: http://www.sbcs-nrs.org.br/rsbcs/

<br>

**BRINGING TOGETHER BRAZILIAN SOIL SCIENTISTS TO SHARE SOIL DATA**

**Alessandro Samuel-Rosa**^1^, **Ricardo Simão Diniz Dalmolin**^1^, **Paulo Ivonir Gubiani**^1^, **Stanley Robson de Medeiros Oliveira**^2^, **Wenceslau Geraldes Teixeira**^3^, **João Herbert Moreira Viana**^4^, **Eloi Ribeiro**^5^, **Carlos Gustavo Tornquist**^6^, **Lúcia Helena Cunha dos Anjos**^7^, **José João Lelis Leal de Souza**^8^, **Marta Vasconcelos Ottoni**^9^, **Paula Suélen Corrêa de Medeiros**^10^, **Diego José Gris**^1^, **Nícolas Augusto Rosin**^1^, Jean Michel Moura Bueno^1^, Humberto Gonçalves dos Santos^3^, Eliseu José Weber^6^, Carlos Alberto Flores^11^, Elias Mendes Costa^7^, Ronaldo Pereira de Oliveira^3^, José Maria Filippini Alba^11^, João Chrisóstomo Pedroso Neto^12^, Fabrício de Araújo Pedron^1^, João Henrique Caviglione^13^, Gustavo Souza Valladares^14^, Carmem Sueze Silva Miranda^15^, José Alexandre Melo Demattê^16^, José Marques Júnior^17^, Diego Silva Siqueira^17^, Renato Eleoterio de Aquino^17^, Nelida Elizabet Quiñonez Silvero^17^, Aline Marques Genú^18^, Tiago Broetto^19^, Luciano Campos Cancian^1^, Pablo Miguel^20^, Jovani Zalamena^21^, André Carnieletto Dotto^16^, Jaime Antonio de Almeida^22^, José Miguel Reichert^1^, Gustavo Ribas Curcio^23^, Leonardo Santos Collier^24^, Waldir de Carvalho Junior^3^, Ademir Fontana^3^, Aline Pacobahyba de Oliveira^3^, Eduardo Saldanha Vogelmann^25^, Fábio Joel Kochem Mallmann^26^, Gustavo de Mattos Vasques^3^, Igo Fernando Lepsch^16^, Jessé Rodrigo Fink^27^, João Carlos Ker^28^, Leandro Souza da Silva^1^, Pedro Luiz de Freitas^3^, Wanderlei Bieluczyk^16^, Tales Tiecher^6^

*^1^ **Universidade Federal de Santa Maria**, ^2^ **Embrapa Informática Agropecuária**, ^3^ **Embrapa Solos**, ^4^ **Embrapa Milho e Sorgo**, ^5^ **ISRIC World Soil Information**, ^6^ **Universidade Federal do Rio Grande do Sul**, ^7^ **Universidade Federal Rural do Rio de Janeiro**, ^8^ **Universidade Federal do Rio Grande do Norte**, ^9^ **Serviço Geológico do Brasil**, ^10^ **Instituto Brasileiro de Geografia e Estatística**, ^11^ Embrapa Clima Temperado, ^12^ Empresa de Pesquisa Agropecuária de Minas Gerais, ^13^ Instituto Agronômico do Paraná, ^14^ Universidade Federal do Piauí, ^15^ Universidade Federal do Vale do São Francisco, ^16^ Universidade de São Paulo, ^17^ Universidade Estadual Paulista, ^18^ Universidade Estadual do Centro Oeste, ^19^ Catena Planejamento Territorial, ^20^ Universidade Federal de Pelotas, ^21^ Universidade Federal de Santa Catarina, ^22^ Universidade do Estado de Santa Catarina, ^23^ Embrapa Florestas, ^24^ Universidade Federal de Goiás, ^25^ Universidade Federal do Rio Grande, ^26^ Universidade Regional Integrada do Alto Uruguai e das Missões, ^27^ Instituto Federal do Paraná, ^28^ Universidade Federal de Viçosa*

**Abstract**: Soil science has produced a great deal of data. Most of the information is published as a single paper, and the primary data is unavailable to other researchers. As data underutilization is a waste of resources and refrains the advancement of knowledge, many isolated soil data rescue and sharing efforts have emerged in the scientific community. Lately, soil scientists have increased their concerns with data discoverability and reusability, and reproducible research. To address these issues, Brazilian soil scientists have recently created a data repository using community-built standards and following open data policies. The Free Brazilian Repository for Open Soil Data – febr, www.ufsm.br/febr – is a centralized repository targeted at storing open soil data and serving it in a standardized and harmonized format. The repository infrastructure was built using open source and/or free (of cost) software, and was primarily designed for the individual management of datasets. A dataset-driven structure helps datasets authors to be properly acknowledged. Moreover, it gives the flexibility to accommodate many types of data of any soil variable. This is accomplished by storing each dataset using a collection of spreadsheets accessible through an online application. Spreadsheets are familiar to any soil scientist, the reason why it is easier to enter, manipulate and visualize soil data in febr. They also facilitate the participation of soil survey experts in the recovery and quality assessment of legacy data. Soil scientists can help in the definition of standards and data management choices through a public discussion forum, febr-forum@googlegroups.com. A comprehensive documentation is available to guide febr maintainers and data contributors. A detailed catalog gives access to the 14 477 soil observations – 42% of them from south and southeastern Brazil – from 232 datasets contained in febr. Global and dataset-specific visualization and search tools and multiple download facilities are available. The latter includes standard file formats and connections with R and QGIS through the febr package. Various products can be derived from data in febr: specialized databases, pedotransfer functions, fertilizer recommendation guides, classification systems, and detailed soil maps. By sharing data through a centralized soil data storing and sharing facility, soil scientists from different fields have the opportunity to increase collaboration and the much needed soil knowledge.

**Keywords**: Legacy soil data; National-scale datasets; Data for scenario modeling; Unified soil data repository; Database design.

**Financial Support**: CAPES.

**Division**: Soils in Space and Time

**Symposia**: Pedometrics -- Reconciling pedometrics and pedology
