---
title: "Bolsa de pesquisa para estudante de graduação da UTFPR Santa Helena"
date: "2018-07-03"
categories: ["bolsa"]
banner: "img/banners/banner-04.png"
author: "Alessandro Samuel-Rosa"
---

O Repositório Brasileiro Livre para Dados Abertos do Solo (___febr___) acaba de receber uma bolsa de iniciação
científica para estudante de graduação da [UTFPR Santa Helena][utfpr]. A bolsa será financiada pela Fundação
Araucária de Apoio ao Desenvolvimento Científico e Tecnológico do Paraná ([FA][fa]) via Programa de Bolsas de
Iniciação Científica ([PIBIC][pibic]). A duração da bolsa será de até __12 meses__, no valor mensal de 
__R$ 400,00__, com vigência de agosto de 2018 até julho de 2019. É a UTFPR Santa Helena reforçando seu 
compromisso com o Programa Nacional de Levantamento e Interpretação de Solos do Brasil 
([PronaSolos][pronasolos]).

[fa]: http://www.fappr.pr.gov.br/
[pibic]: http://www.fappr.pr.gov.br/arquivos/File/chamadas2018/2018_CP02_PibicPibit.pdf
[pronasolos]: http://www.imprensanacional.gov.br/web/guest/materia/-/asset_publisher/Kujrw0TZC2Mb/content/id/26572788/do1-2018-06-20-decreto-n-9-414-de-19-de-junho-de-2018-26572694
[utfpr]: http://portal.utfpr.edu.br/

## Como se inscrever?

As inscrições vão até às 18 horas do dia __05 de julho de 2018__, quinta-feira, na UTFPR Santa Helena, sala E08, 
com [Alessandro Samuel-Rosa][alessandro]. Uma breve entrevista será feita no momento da inscrição, na qual será
avaliado o potencial discente de realizar as atividades previstas no projeto ([link][projeto]) e descritas no 
plano de trabalho ([link][plano]). O resultado será publicado no dia seguinte, __06 de julho de 2018__,
sexta-feira.

[projeto]: https://cloud.utfpr.edu.br/index.php/s/wuWaPRHnIDEkrxP
[plano]: https://cloud.utfpr.edu.br/index.php/s/PC3XWdHwDact3YX
[alessandro]: http://samuel-rosa.github.io/

A __documentação__ exigida para a inscrição é:

1. Declaração de matrícula em curso de graduação da UTFPR Santa Helena, e
2. Declaração de próprio punho de que não possui vínculo empregatício e de que não acumula bolsa.

## Das obrigações

1. Estar regularmente matriculado em curso de graduação da UTFPR Santa Helena,
2. Não ter vínculo empregatício e dedicar-se às atividades acadêmicas e de pesquisa,
    + Estágios serão considerados compatíveis com a dedicação às atividades acadêmicas e de pesquisa apenas
      quando realizados em período não letivo,
3. Receber apenas esta modalidade de bolsa, sendo vedada a acumulação com outras, exceto aquelas de programas
   oficiais que possuem objetivos assistenciais, de manutenção ou de permanência,
4. Ter currículo atualizado, em português, na [Plataforma Lattes do CNPq][lattes] e, em inglês, no
   [ResearchGate][rg] e no [ORCID][orcid], incluindo foto e apresentação pessoal,
5. Desenvolver em conjunto com o orientador, plano de atividades da pesquisa a ser realizada, com dedicação 
   de 20 (vinte) horas semanais,
6. Apresentar os resultados finais do plano de atividades, sob a forma de exposição oral e/ou painel, no SICITE 
   2019 da UTFPR, e atuar como monitor se solicitado,
7. Elaborar relatórios para apreciação do orientador,
8. Incluir o nome do orientador nas publicações e nos trabalhos apresentados em congressos e seminários, cujos 
   resultados contaram com a participação efetiva deste,
9. Responsabilizar-se pela identificação visual obrigatória da Fundação Araucária e da Secretaria da 
   Ciência, Tecnologia e Ensino Superior como financiadora do PIBIC/PIBIT, nas publicações de trabalhos
   apresentados em eventos de qualquer natureza e em qualquer meio de divulgação, e
10. Participar, com matrícula, da disciplina de [Gênese e Morfologia do Solo][genese] ofertada pela Coordenação
    do Curso de Agronomia da UTFPR Santa Helena no segundo semestre letivo de 2018.

[lattes]: http://lattes.cnpq.br/
[rg]: https://www.researchgate.net/
[orcid]: https://orcid.org/
[genese]: http://www.utfpr.edu.br/patobranco/estrutura-universitaria/diretorias/dirgrad/cursos/coagr/documentos/planos_de_ensino_560-1/genese-e-morfologia-do-solo-a-gs24g

_Nota: Bolsistas da Fundação Araucária precisam ter conta bancária na Caixa Econômica Federal._
