---
title: "Bolsa de extensão para estudante de graduação da UTFPR Santa Helena"
date: "2018-06-21"
categories: ["notícia"]
banner: "img/banners/banner-03.png"
author: "Alessandro Samuel-Rosa"
---

O Repositório Brasileiro Livre para Dados Abertos do Solo (___febr___) acaba de ser reconhecido como Projeto de
Extensão da Universidade Tecnológica Federal do Paraná ([UTFPR][utfpr]). Com isso, o ___febr___ terá direito a
bolsas para estudantes de graduação, apoio financeiro para custeio do projeto e para representar a UTFPR em 
eventos de interesse da instituição por um período de até três anos. Isso permitirá aperfeiçoar o ___febr___ 
como plataforma coletiva de compartilhamento de dados do solo no Brasil, ampliando o acesso dos vários 
segmentos da sociedade aos dados do solo produzidos nas instituições de ensino e pesquisa brasileiras -- a
primeira contribuição da UTFPR Santa Helena para o Programa Nacional de Levantamento e Interpretação de Solos 
do Brasil ([PronaSolos][pronasolos]).

[utfpr]: http://portal.utfpr.edu.br/
[pronasolos]: http://www.imprensanacional.gov.br/web/guest/materia/-/asset_publisher/Kujrw0TZC2Mb/content/id/26572788/do1-2018-06-20-decreto-n-9-414-de-19-de-junho-de-2018-26572694

## Você quer uma bolsa?

Estamos selecionando estudante cotista de graduação da UTFPR Santa Helena para ser bolsista do ___febr___. A 
bolsa será financiada pela Fundação Araucária de Apoio ao Desenvolvimento Científico e Tecnológico do Paraná
([FA][fa]) via Programa Institucional de Apoio a Inclusão Social -- Pesquisa e Extensão Universitária 
([PIBIS][pibis]). A duração da bolsa será de até __12 meses__, no valor mensal de __R$ 400,00__.

[fa]: http://www.fappr.pr.gov.br/
[pibis]: http://www.fappr.pr.gov.br/arquivos/File/chamadas2018/2018_CP03_Pibis.pdf

A inscrição no processo seletivo vai até ao meio-dia de __26 de junho de 2018__, próxima terça-feira, na 
UTFPR Santa Helena, sala E08, com [Alessandro Samuel-Rosa][alessandro]. Uma breve entrevista será feita no 
momento da inscrição, na qual será avaliado o potencial discente de realizar as atividades previstas no projeto
([link][projeto]) e descritas no plano de trabalho ([link][plano]). O resultado será publicado no dia 
seguinte, __27 de junho de 2018__, quarta-feira. O incío da vigência da bolsa está previsto para agosto de 2018.

A __documentação__ exigida para a inscrição é:

1. Declaração de matrícula em curso de graduação da UTFPR Santa Helena,
2. Declaração de próprio punho de que não acumula bolsa, conforme consta na página de editais da UTFPR 
   ([link][declaracao]), e
3. Declaração emitida pelo DERAC da UTFPR Santa Helena confirmando o ingresso na modalidade de cotista.

[projeto]: https://cloud.utfpr.edu.br/index.php/s/bun8guNDsSI1Ibf
[plano]: https://cloud.utfpr.edu.br/index.php/s/aJzyiKg7VhXxcvU
[alessandro]: http://samuel-rosa.github.io/
[declaracao]: http://www.utfpr.edu.br/estrutura-universitaria/diretorias-de-gestao/dircom/noticias/noticias/link/DECLARAODENOACMULODEBOLSA.pdf

Das __obrigações__:

1. Executar as atividades elencadas no Plano de Trabalho, com carga horária de 20 horas semanais,
2. Estar regularmente matriculado em curso de graduação da UTFPR Santa Helena e ter no mínimo mais 12 meses de
   curso a cumprir,
3. Fazer referência a sua condição de bolsista nas publicações e trabalhos apresentados, incluindo menção de 
   agradecimento à organização financiadora da bolsa,
4. Não ter vínculo empregatício ou estágio remunerado e dedicar-se integralmente às atividades acadêmicas
   e ao desenvolvimento das atividades elencadas no Plano de Trabalho,
5. Estar recebendo apenas esta modalidade de bolsa, sendo vedada acumulação com outros Programas (inclusive 
   bolsa permanência), exceto auxílio estudantil pago pelo Núcleo de Apoio ao Estudante (NUAPE),
6. Não compartilhar a bolsa com outros estudantes, sendo expressamente vedada a divisão da mensalidade de uma
   bolsa entre dois ou mais estudantes,
7. Elaborar um artigo do projeto para submissão ao SEI,
8. Participar do SEI com recursos da bolsa, e
9. Atuar como monitor do SEI, da UTFPR, sempre que solicitado.

_Nota: O resultado final do Edital 01/2018 da Pró-Reitoria de Relações Empresarias e Comunitárias (PROREC) da Universidade Tecnológica Federal do Paraná pode ser consultado em http://portal.utfpr.edu.br/editais/relacoes-empresariais-e-comunitarias/reitoria/extensao/edital-extensao-01-2018
_
